criterion:
  name: distanceLoss
  min_distance: 0.12

aux_criterion:
  curl_loss:
    weight: 0.0
  tv_loss:
    weight: 0.0
    norm: False

test_criterion:
  name: nmse

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.000

lr_scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

temp_scheduler:
  name: temperature
  lr: 0.01
  lr_min: 1e-5

run:

run:
  experiment: "phc_local_search"
  n_epochs: 100
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 10
  fp16: False
  wandb:
    project: robust_inverse_design
    entity: scopex
    name: local_search

quantize:
  weight_bit: 32
  input_bit: 32

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "phc/local_search/train_local_search"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "Repara_PhC_1x1"
  device_cfg:
    num_in_ports: 1
    num_out_ports: 1
    box_size: [10, 10]
    wg_width: (1.7320508076, 1.7320508076)
    port_len: 3
    taper_width: 1.7320508076
    taper_len: 2
    eps_r: eps_si
    eps_bg: eps_sio2
  sim_cfg:
    resolution: 20
    border_width: [0, 1]
    PML: (2, 2)
    record_interval: 0.3
    store_fields: ["Ez"]
    until: 250
    stop_when_decay: False
  purturbation: False
  num_rows_perside: 6
  num_cols: 8

debug:
  verbose: 1

plot:
  train: True
  valid: True
  test: True
  interval: 1
  dir_name: local_search
